services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.mac
    volumes:
      - ./frontend:/app/frontend
      - playwright_browsers:/root/.cache/ms-playwright
    ports:
      - "3000:3000"
    command: npm run build-and-dev
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "8000:8000"
    environment:
      - "DJANGO_SUPERUSER_PASSWORD=${DJANGO_SUPERUSER_PASSWORD}"
      - "DJANGO_SUPERUSER_USERNAME=${DJANGO_SUPERUSER_USERNAME}"
      - "DJANGO_SUPERUSER_EMAIL=${DJANGO_SUPERUSER_EMAIL}"
    command: sh /app/backend/start.sh
    depends_on:
      - db

  db:
    image: postgres:17.5-alpine3.21
    ports:
        - "5432"
    environment:
      - "POSTGRES_DB=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  playwright_browsers:
